"""
NarrativeSummary DynamoDB table abstraction.

Table schema (AWS-provisioned — aligned with infra)
----------------------------------------------------
PK  esn          (S)  — ESN value
SK  createdAt    (S)  — ISO-8601 UTC

assessmentId (S)  — regular attribute; GSI-1 PK
persona      (S)  — RE | OE — persona at generation time
summary      (S)  — narrative text generated by A2
updatedAt    (S)  — ISO-8601 UTC

GSI-1: ns-assessment-index (PK=assessmentId, ALL)
  → LIMIT=1 ScanIndexForward=False gives latest narrative for an assessmentId
"""

from __future__ import annotations

from datetime import timezone, datetime
from typing import Any

from data_service import config

# ── In-memory store ────────────────────────────────────────────────────────────
_STORE: dict[str, dict[str, Any]] = {}


def _now() -> str:
    return datetime.now(tz=timezone.utc).isoformat()


# ── Public API ─────────────────────────────────────────────────────────────────


def write_narrative_summary(esn: str, assessment_id: str, persona: str, summary: str) -> None:
    """Persist narrative summary for an assessment (versioned write — new item per generation)."""
    if config.USE_MOCK_ASSESSMENTS:
        _STORE[assessment_id] = {
            "esn": esn,
            "createdAt": _now(),
            "assessmentId": assessment_id,
            "persona": persona,
            "summary": summary,
            "updatedAt": _now(),
        }
    else:  # pragma: no cover
        import boto3  # noqa: PLC0415

        table = boto3.resource(
            "dynamodb",
            region_name=config.DYNAMODB_REGION,
            endpoint_url=config.DYNAMODB_ENDPOINT_URL,
        ).Table(config.NARRATIVE_SUMMARY_TABLE)
        created_at = _now()
        table.put_item(
            Item={
                "esn": esn,               # table PK
                "createdAt": created_at,  # table SK
                "assessmentId": assessment_id,
                "persona": persona,
                "summary": summary,
                "updatedAt": created_at,
            }
        )


def read_narrative_summary(assessment_id: str) -> dict[str, Any] | None:
    """Return the latest narrative summary item for an assessment, or None if not found.

    Mock: direct lookup by assessmentId.
    Live: GSI-1 Query(assessmentId=X, ScanIndexForward=False, Limit=1).
    """
    if config.USE_MOCK_ASSESSMENTS:
        return _STORE.get(assessment_id)
    else:  # pragma: no cover
        import boto3  # noqa: PLC0415
        from boto3.dynamodb.conditions import Key  # noqa: PLC0415
        from botocore.exceptions import ClientError  # noqa: PLC0415

        table = boto3.resource(
            "dynamodb",
            region_name=config.DYNAMODB_REGION,
            endpoint_url=config.DYNAMODB_ENDPOINT_URL,
        ).Table(config.NARRATIVE_SUMMARY_TABLE)
        try:
            resp = table.query(
                IndexName=config.APP_PREFIX + "ns-assessment-index",
                KeyConditionExpression=Key("assessmentId").eq(assessment_id),
                ScanIndexForward=False,
                Limit=1,
            )
            items = resp.get("Items", [])
            return items[0] if items else None
        except ClientError as exc:
            if exc.response["Error"]["Code"] == "ResourceNotFoundException":
                return None
            raise


def clear() -> None:
    """Remove all records — used between tests."""
    _STORE.clear()
